---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    services:
      db:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        volumes:
          - dev-db-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=devdb
          - POSTGRES_USER=devuser
          - POSTGRES_PASSWORD=changeme
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN_2 }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"